trigger:
- main

pool:
  name: Default

variables:
  buildId: 'PythonProject_SAST'
  fortifyBin: 'C:\Program Files\Fortify\OpenText_SAST_Fortify_26.1.0\bin'
  pythonPath: 'C:\Users\m-xz9\AppData\Local\Microsoft\WindowsApps'
  sscUrl: 'http://192.168.1.131:8081/ssc'
  FortifyAuthToken: 'NjdjZjBhNzgtODIyOS00NDYzLWJhYmEtNjIxZGU5ODE3M2Y0'
  fortifyProject: 'test-azure'      # SSC'deki Application adı
  fortifyVersion: 'dev'                # SSC'deki Version adı

steps:
- checkout: self

- task: CmdLine@2
  displayName: 'Fortify - Clean'
  inputs:
    script: '"$(fortifyBin)\sourceanalyzer.exe" -b $(buildId) -clean'

- task: CmdLine@2
  displayName: 'Fortify - Translate (Python kaynaklarını analiz et)'
  inputs:
    script: '"$(fortifyBin)\sourceanalyzer.exe" -b $(buildId) -python-path "$(pythonPath)" "$(Build.SourcesDirectory)\**\*.py"'

- task: CmdLine@2
  displayName: 'Fortify - Scan'
  inputs:
    script: '"$(fortifyBin)\sourceanalyzer.exe" -b $(buildId) -scan -f "$(Build.ArtifactStagingDirectory)\results.fpr"'

- task: PublishBuildArtifacts@1
  displayName: 'FPR dosyasını yayınla'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\results.fpr'
    ArtifactName: 'FortifyResults'

- task: CmdLine@2
  displayName: 'Fortify - SSC ye Upload'
  inputs:
    script: '"$(fortifyBin)\fortifyclient.bat" uploadFPR -file "$(Build.ArtifactStagingDirectory)\results.fpr" -url $(sscUrl) -authtoken $(FortifyAuthToken) -project "$(fortifyProject)" -applicationVersion "$(fortifyVersion)"'
